### ISSUE TITLE
results for people for a page sometimes returns html_urls from the wrong PopIt instance (!)

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#729]
This is alarming - when getting successive pages from a particular PopIt instance you might get a page of results from a completely different instance for one of those requests. For example, with this script in YourNextMP (to look for broken data, but that's incidental - we only care about the value of `url` for each person):

* https://github.com/mysociety/yournextmp-popit/blob/01d396e883d9ca9ed63c8d6fb18c360fa80d04d9/candidates/management/commands/candidates_find_missing_post_ids.py

... you might get output like this:

* https://gist.github.com/mhl/e163cdc40fdc88556687

(Look for `"page": 18`)

Note the the `person['url']` values are all from `yournextmp.popit.mysocity.org` except for page 18, where they're from `legisladores-ar.popit.mysociety.org`. The page this happens on seems to be random and the PopIt instance that the results are from is similarly random. For example, on another run, page 11 returned results with `url` from `za-new-import.popit.mysociety.org` - the request for page 11 was uncontroversial, here's the ngrep dump of that request:

```
  GET /api/v0.1/persons?per_page=100&page=11 HTTP/1.1..Host: yournextmp.popit.mysociety.
  org..Accept-Encoding: gzip, deflate..accept: application/json..User-Agent: python-requ
  ests/2.4.1 CPython/2.7.6 Linux/3.13.0-44-generic..Connection: keep-alive..content-type
  : application/json..Authorization: Basic 
```

**Comment by chrismytton** [comment]
I believe this is because we're setting schema level options for the base urls, which is leaking across requests. The fix is to move away from this flawed approach and start using request level options. I've started [a branch to fix this specific issue](https://github.com/mysociety/popit-api/compare/729-pagination-race-condition), but hopefully the approach can be used to fix the general case of using schema level options for configuration.
