### ISSUE TITLE
Search Index not returning results for sinar-malaysia

### ISSUE THREAD

**Issue by kaerumy** [mysociety/popit#846]
Search term 'Nawawi'

https://sinar-malaysia.popit.mysociety.org/search?q=nawawi

No results for: 

person id: 545e430b5222837c2c05893a label "Nawawi Bin Ahmad"
person id: 545e465a5222837c2c059177 label "Nawawi Ahmad"

Both of them are not showing in popit search api results.

**Comment by kaerumy** [comment]
This is causing quite a bit of a problem whenever it happens, as our researchers will keep adding duplicate names, thinking the person doesn't exist in the database.

**Comment by chrismytton** [comment]
@kaerumy It looks like person `545e430b5222837c2c05893a` is the second person in the search results - "Nawawi Ahmad".

Person `545e465a5222837c2c059177` isn't appearing in the search results because they have an invalid `birth_date`. If you look at [the API page for that person](https://sinar-malaysia.popit.mysociety.org/api/v0.1/persons/545e465a5222837c2c059177) you can see that their date of birth is `1961 -5 -3`, when it should be `1961-5-3`. If you fix the `birth_date` then that document should correctly appear in the search results.

**Comment by kaerumy** [comment]
OK thanks fixed. Just letting you know that the bad dates were added by our interns, through the Popit UI which doesn't seem to be using the API in submitting values (and seems to be the source of our problems).

We're cleaning it up as best as possible, until our new API based UIs are done.

Thanks
